
// Objective-C API for talking to the following Go packages
//
//	github.com/matrix-org/dendrite/build/gobind-libp2p
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Radixmobile_FRAMEWORK_H__
#define __Radixmobile_FRAMEWORK_H__

#include "Radixmobile.objc.h"
#include "Universe.objc.h"

#endif
