# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'
ENV['SWIFT_VERSION'] = '5'
use_frameworks!


target 'sendingnetworkSDK-oc-demo' do
  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for sendingnetworkSDK-oc-dem
  pod "SendingnetworkSDK"
  pod "web3.swift"

end
