# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'sendingnetwork-ios-demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for test-swift
#  pod 'OLMKit', '~> 3.2.5', :inhibit_warnings => true
#  pod 'Realm', '10.27.0'
#  pod 'TrustWalletCore', '~> 2.9.2'
#  pod 'KeychainAccess'
  pod 'web3.swift'
  pod 'SnapKit'
  
  pod 'SendingnetworkSDK', :path => '../SendingnetworkSDK.podspec'

end
